// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2jm6J63232MWhKta0CYWfFHSDENGw58',
    appId: '1:334141358278:web:f6f58550763dfcdafa17c7',
    messagingSenderId: '334141358278',
    projectId: 'authdogsapp',
    authDomain: 'authdogsapp.firebaseapp.com',
    storageBucket: 'authdogsapp.firebasestorage.app',
    measurementId: 'G-8HRLGMJ61M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyuI3Kyfwc99eJzJIU5FyiFganehoyBuI',
    appId: '1:334141358278:android:b50b726884b29c94fa17c7',
    messagingSenderId: '334141358278',
    projectId: 'authdogsapp',
    storageBucket: 'authdogsapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl2jm6J63232MWhKta0CYWfFHSDENGw58',
    appId: '1:334141358278:web:5268fb43e3d418f5fa17c7',
    messagingSenderId: '334141358278',
    projectId: 'authdogsapp',
    authDomain: 'authdogsapp.firebaseapp.com',
    storageBucket: 'authdogsapp.firebasestorage.app',
    measurementId: 'G-YRGVZLG2BM',
  );

}